<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-09-08T10:48:02Z" name="Authentication" finished-at="2019-09-08T10:51:29Z" duration-ms="206823">
    <groups>
    </groups>
    <test started-at="2019-09-08T10:48:02Z" name="LoginTest" finished-at="2019-09-08T10:51:29Z" duration-ms="206823">
      <class name="LoginFormTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:48:02Z" name="launchApplication" finished-at="2019-09-08T10:50:39Z" duration-ms="157040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="check_If_all_Required_Elements_Are_Displayed()[pri:1, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:50:39Z" name="check_If_all_Required_Elements_Are_Displayed" finished-at="2019-09-08T10:50:49Z" duration-ms="10032" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_If_all_Required_Elements_Are_Displayed -->
        <test-method signature="login_With_Correct_Credentials(java.lang.String, java.lang.String)[pri:2, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:50:49Z" name="login_With_Correct_Credentials" finished-at="2019-09-08T10:51:20Z" depends-on-methods="LoginFormTest.check_If_all_Required_Elements_Are_Displayed" duration-ms="30846" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test1@automationpractice.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[28328719@Aut?!]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for presence of element located by: By.xpath: //div[@class="form-group form-ok"]/input[@id="email"] (tried for 30 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.xpath: //div[@class="form-group form-ok"]/input[@id="email"] (tried for 30 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
at utils.Utils.waitForElementPresence(Utils.java:19)
at pages.LoginForm.getEmailHighlightedGreen(LoginForm.java:68)
at LoginFormTest.login_With_Correct_Credentials(LoginFormTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="form-group form-ok"]/input[@id="email"]"}
  (Session info: chrome=76.0.3809.132)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-PJLCLMT', ip: '192.168.88.248', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.132, chrome: {chromedriverVersion: 76.0.3809.68 (420c9498db8ce..., userDataDir: C:\Users\oncha\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:52459}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: f893c52217dedcea8e137309b0662bf3
*** Element info: {Using=xpath, value=//div[@class="form-group form-ok"]/input[@id="email"]}
at jdk.internal.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_With_Correct_Credentials -->
        <test-method signature="login_With_Invalid_Email_Address_Valid_Password(java.lang.String, java.lang.String)[pri:3, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:51:20Z" name="login_With_Invalid_Email_Address_Valid_Password" finished-at="2019-09-08T10:51:23Z" depends-on-methods="LoginFormTest.check_If_all_Required_Elements_Are_Displayed" duration-ms="2703" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[automationpractice.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[28328719@Aut?!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_With_Invalid_Email_Address_Valid_Password -->
        <test-method signature="login_With_Valid_Email_Address_Invalid_Password(java.lang.String, java.lang.String)[pri:4, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:51:23Z" name="login_With_Valid_Email_Address_Invalid_Password" finished-at="2019-09-08T10:51:28Z" depends-on-methods="LoginFormTest.check_If_all_Required_Elements_Are_Displayed" duration-ms="5449" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test1@automationpractice.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[243544657@efg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at LoginFormTest.login_With_Valid_Email_Address_Invalid_Password(LoginFormTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_With_Valid_Email_Address_Invalid_Password -->
        <test-method is-config="true" signature="close_All()[pri:0, instance:LoginFormTest@7ff95560]" started-at="2019-09-08T10:51:28Z" name="close_All" finished-at="2019-09-08T10:51:29Z" duration-ms="707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_All -->
      </class> <!-- LoginFormTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Authentication -->
</testng-results>
